export const cat_idle_path_image ="images/cat_Idle.gif"
export const cat_run_path_image ="images/cat_run.gif"
export const rat_idle_path_image ="images/rat_Idle.gif"
export const rat_run_path_image ="images/rat_run.gif"
export const cat_jump_path_image ="images/cat_jump.gif"
export const terrain_path_image ="images/Terrain.png"
export const cat_attack_path_image ="images/catAttack.gif"
export const background_path_image ="images/background.png"
export const canvas = document.querySelector("canvas")
